# Generated by Django 3.0.8 on 2020-07-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Teachers')),
                ('teaching_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.AllSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, unique=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('admission_year', models.IntegerField()),
                ('dob', models.DateField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_in', to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/profile_pics')),
                ('abcd', models.CharField(max_length=25)),
                ('hobby', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=30)),
                ('no_of_copies', models.IntegerField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.AllSubject')),
            ],
        ),
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Students')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attendance', models.DateField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=7)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Students')),
            ],
        ),
    ]
