# Generated by Django 3.0.7 on 2020-06-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Teachers')),
                ('teaching_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.AllSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, unique=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('admission_year', models.TextField()),
                ('dob', models.DateField(db_column='DOB')),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=30)),
                ('no_of_copies', models.IntegerField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.AllSubject')),
            ],
        ),
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Students')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attendance', models.DateTimeField()),
                ('attendance_status', models.CharField(max_length=7)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Class')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Students')),
            ],
        ),
    ]
