# Generated by Django 3.0.8 on 2020-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_remove_profile_abcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gallery',
            field=models.FileField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
