# Generated by Django 3.0.7 on 2020-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_allsubject_attendance_bookdistribution_class_classsubjects_library_registration_role_students_teache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=7),
        ),
        migrations.AlterField(
            model_name='students',
            name='admission_year',
            field=models.IntegerField(),
        ),
    ]
