# Generated by Django 3.0.8 on 2020-07-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_profile_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gallery',
        ),
    ]
