# Generated by Django 3.0.7 on 2020-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20200623_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='d', upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
