# Generated by Django 3.0.7 on 2020-06-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
