# Generated by Django 3.0.8 on 2020-07-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
