# Generated by Django 3.0.7 on 2020-06-24 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_of_attendance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
