# Generated by Django 3.0.7 on 2020-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_auto_20200624_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
