# Generated by Django 3.0.7 on 2020-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_auto_20200625_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
