# Generated by Django 3.0.8 on 2020-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='files',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
