# Generated by Django 3.0.7 on 2020-06-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('restapp', '0011_remove_registration_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
