# Generated by Django 3.0.8 on 2020-07-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_gallery_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='files',
        ),
    ]
