# Generated by Django 3.0.8 on 2020-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0012_remove_gallery_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='files',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
