# Generated by Django 3.0.7 on 2020-06-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0012_auto_20200626_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
