# Generated by Django 3.0.8 on 2020-07-08 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapp', '0013_auto_20200708_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='MyUploads',
        ),
    ]
