# Generated by Django 3.0.8 on 2020-07-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapp', '0014_auto_20200708_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploads',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyUploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
