# Generated by Django 3.0.7 on 2020-06-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapp', '0015_auto_20200626_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_in', to='restapp.Class'),
        ),
    ]
