# Generated by Django 3.0.7 on 2020-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0017_auto_20200627_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_of_attendance',
            field=models.DateTimeField(),
        ),
    ]
