# Generated by Django 3.0.7 on 2020-06-27 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0018_auto_20200627_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_of_attendance',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 18, 16, 32, 953283, tzinfo=utc)),
        ),
    ]
